---
language: python
dist: xenial

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install libssl-dev python-setuptools
  - sudo pip install molecule wheel ansible

script:
  - sudo python2.7 /home/travis/.local/bin/molecule test --destroy=never 